#!/bin/bash

python chapter04-train.py --dataset femnist --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm fedavg --step_size 1e-3 --weighting_scheme adjacency --output_directory simulations --log --device cuda
python chapter04-train.py --dataset femnist --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm fedavg --step_size 1e-3 --weighting_scheme adjacency --class_imbalance 10 --data_imbalance 1 --output_directory simulations --log --device cuda
python chapter04-train.py --dataset femnist --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm fedavg --step_size 1e-3 --weighting_scheme adjacency --output_directory simulations --nonconvex --log --device cuda
python chapter04-train.py --dataset femnist --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm fedavg --step_size 1e-3 --weighting_scheme adjacency --class_imbalance 10 --data_imbalance 1 --output_directory simulations --nonconvex --log --device cuda

python chapter04-train.py --dataset femnist --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm fedprox --alpha 0.1 --step_size 1e-3 --weighting_scheme adjacency --output_directory simulations --log --device cuda
python chapter04-train.py --dataset femnist --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm fedprox --alpha 0.1 --step_size 1e-3 --weighting_scheme adjacency --class_imbalance 10 --data_imbalance 1 --output_directory simulations --log --device cuda
python chapter04-train.py --dataset femnist --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm fedprox --alpha 0.1 --step_size 1e-3 --weighting_scheme adjacency --output_directory simulations --nonconvex --log --device cuda
python chapter04-train.py --dataset femnist --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm fedprox --alpha 0.1 --step_size 1e-3 --weighting_scheme adjacency --class_imbalance 10 --data_imbalance 1 --output_directory simulations --nonconvex --log --device cuda

python chapter04-train.py --dataset femnist --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.9 --step_size 1e-3 --weighting_scheme adjacency --output_directory simulations --log --device cuda
python chapter04-train.py --dataset femnist --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.9 --step_size 1e-3 --weighting_scheme adjacency --class_imbalance 10 --data_imbalance 1 --output_directory simulations --log --device cuda
python chapter04-train.py --dataset femnist --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.9 --step_size 1e-3 --weighting_scheme adjacency --output_directory simulations --nonconvex --log --device cuda
python chapter04-train.py --dataset femnist --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.9 --step_size 1e-3 --weighting_scheme adjacency --class_imbalance 10 --data_imbalance 1 --output_directory simulations --nonconvex --log --device cuda

python chapter04-train.py --dataset femnist --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.7 --step_size 1e-3 --weighting_scheme adjacency --output_directory simulations --log --device cuda
python chapter04-train.py --dataset femnist --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.7 --step_size 1e-3 --weighting_scheme adjacency --class_imbalance 10 --data_imbalance 1 --output_directory simulations --log --device cuda
python chapter04-train.py --dataset femnist --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.7 --step_size 1e-3 --weighting_scheme adjacency --output_directory simulations --nonconvex --log --device cuda
python chapter04-train.py --dataset femnist --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.7 --step_size 1e-3 --weighting_scheme adjacency --class_imbalance 10 --data_imbalance 1 --output_directory simulations --nonconvex --log --device cuda

python chapter04-train.py --dataset femnist --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.5 --step_size 1e-3 --weighting_scheme adjacency --output_directory simulations --log --device cuda
python chapter04-train.py --dataset femnist --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.5 --step_size 1e-3 --weighting_scheme adjacency --class_imbalance 10 --data_imbalance 1 --output_directory simulations --log --device cuda
python chapter04-train.py --dataset femnist --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.5 --step_size 1e-3 --weighting_scheme adjacency --output_directory simulations --nonconvex --log --device cuda
python chapter04-train.py --dataset femnist --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.5 --step_size 1e-3 --weighting_scheme adjacency --class_imbalance 10 --data_imbalance 1 --output_directory simulations --nonconvex --log --device cuda

python chapter04-train.py --dataset cifar10 --convergence_rounds_threshold 0.30 --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm fedavg --step_size 1e-3 --weighting_scheme adjacency --output_directory simulations --log --device cuda
python chapter04-train.py --dataset cifar10 --convergence_rounds_threshold 0.30 --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm fedavg --step_size 1e-3 --weighting_scheme adjacency --class_imbalance 100 --data_imbalance 1 --output_directory simulations --log --device cuda
python chapter04-train.py --dataset cifar10 --convergence_rounds_threshold 0.30 --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm fedavg --step_size 1e-3 --weighting_scheme adjacency --output_directory simulations --nonconvex --log --device cuda
python chapter04-train.py --dataset cifar10 --convergence_rounds_threshold 0.30 --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm fedavg --step_size 1e-3 --weighting_scheme adjacency --class_imbalance 100 --data_imbalance 1 --output_directory simulations --nonconvex --log --device cuda

python chapter04-train.py --dataset cifar10 --convergence_rounds_threshold 0.30 --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm fedprox --alpha 0.1 --step_size 1e-3 --weighting_scheme adjacency --output_directory simulations --log --device cuda
python chapter04-train.py --dataset cifar10 --convergence_rounds_threshold 0.30 --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm fedprox --alpha 0.1 --step_size 1e-3 --weighting_scheme adjacency --class_imbalance 100 --data_imbalance 1 --output_directory simulations --log --device cuda
python chapter04-train.py --dataset cifar10 --convergence_rounds_threshold 0.30 --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm fedprox --alpha 0.1 --step_size 1e-3 --weighting_scheme adjacency --output_directory simulations --nonconvex --log --device cuda
python chapter04-train.py --dataset cifar10 --convergence_rounds_threshold 0.30 --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm fedprox --alpha 0.1 --step_size 1e-3 --weighting_scheme adjacency --class_imbalance 100 --data_imbalance 1 --output_directory simulations --nonconvex --log --device cuda

python chapter04-train.py --dataset cifar10 --convergence_rounds_threshold 0.30 --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.9 --step_size 1e-3 --weighting_scheme adjacency --output_directory simulations --log --device cuda
python chapter04-train.py --dataset cifar10 --convergence_rounds_threshold 0.30 --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.9 --step_size 1e-3 --weighting_scheme adjacency --class_imbalance 100 --data_imbalance 1 --output_directory simulations --log --device cuda
python chapter04-train.py --dataset cifar10 --convergence_rounds_threshold 0.30 --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.9 --step_size 1e-3 --weighting_scheme adjacency --output_directory simulations --nonconvex --log --device cuda
python chapter04-train.py --dataset cifar10 --convergence_rounds_threshold 0.30 --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.9 --step_size 1e-3 --weighting_scheme adjacency --class_imbalance 100 --data_imbalance 1 --output_directory simulations --nonconvex --log --device cuda

python chapter04-train.py --dataset cifar10 --convergence_rounds_threshold 0.30 --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.7 --step_size 1e-3 --weighting_scheme adjacency --output_directory simulations --log --device cuda
python chapter04-train.py --dataset cifar10 --convergence_rounds_threshold 0.30 --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.7 --step_size 1e-3 --weighting_scheme adjacency --class_imbalance 100 --data_imbalance 1 --output_directory simulations --log --device cuda
python chapter04-train.py --dataset cifar10 --convergence_rounds_threshold 0.30 --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.7 --step_size 1e-3 --weighting_scheme adjacency --output_directory simulations --nonconvex --log --device cuda
python chapter04-train.py --dataset cifar10 --convergence_rounds_threshold 0.30 --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.7 --step_size 1e-3 --weighting_scheme adjacency --class_imbalance 100 --data_imbalance 1 --output_directory simulations --nonconvex --log --device cuda

python chapter04-train.py --dataset cifar10 --convergence_rounds_threshold 0.30 --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.5 --step_size 1e-3 --weighting_scheme adjacency --output_directory simulations --log --device cuda
python chapter04-train.py --dataset cifar10 --convergence_rounds_threshold 0.30 --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.5 --step_size 1e-3 --weighting_scheme adjacency --class_imbalance 100 --data_imbalance 1 --output_directory simulations --log --device cuda
python chapter04-train.py --dataset cifar10 --convergence_rounds_threshold 0.30 --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.5 --step_size 1e-3 --weighting_scheme adjacency --output_directory simulations --nonconvex --log --device cuda
python chapter04-train.py --dataset cifar10 --convergence_rounds_threshold 0.30 --n_agents 100 --n_iterations 200 --n_epochs 10 --algorithm ours --beta 0.5 --step_size 1e-3 --weighting_scheme adjacency --class_imbalance 100 --data_imbalance 1 --output_directory simulations --nonconvex --log --device cuda